name: Release Nightly

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:

  release-nightly:
    name: Nightly release
    if: github.event_name != 'schedule' || github.repository == 'keycloak/keycloak-nodejs-connect'
    uses: ./.github/workflows/x-release.yml
    with:
      gh-org: mposolda # TODO:mposolda
      branch: ${{ github.ref_name }}
      tag: nightly
      nightly: true
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
