name: X Release

on:
  workflow_call:
    inputs:
      gh-org:
        required: true
        type: string
      branch:
        required: true
        type: string
      tag:
        required: true
        type: string
      nightly:
        required: true
        type: boolean
    secrets:
      GH_TOKEN:
        required: true
#     TODO:mposolda uncomment
#      NPM_TOKEN:
#        required: true

concurrency: rel-${{ github.ref }}

defaults:
  run:
    shell: bash

jobs:

  show-inputs:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Github organization: ${{ inputs.gh-org }}  " >> $GITHUB_STEP_SUMMARY
          echo "Branch: ${{ inputs.branch }}  " >> $GITHUB_STEP_SUMMARY
          echo "Target tag: ${{ inputs.tag }}  " >> $GITHUB_STEP_SUMMARY
          echo "Is nightly build: ${{ inputs.nightly }}  " >> $GITHUB_STEP_SUMMARY

  create-tags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - name: Create version commit
        if: ${{ !inputs.nightly }}
        run: |
          ./set-version.sh ${{ inputs.tag }}
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git commit -a -m "Set version to ${{ inputs.tag }}"

      - name: Tag commit
        run: git tag --force ${{ inputs.tag }}

      - name: Push changes
        run: git push --force origin refs/tags/${{ inputs.tag }}

  create-gh-releases:
    runs-on: ubuntu-latest
    needs: [create-tags]
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Check if release exists
        id: release-exists
        run: >
          echo "release-exists=$(
            if ( gh release view ${{ inputs.tag }} --repo ${{ inputs.gh-org }}/keycloak-nodejs-connect &> /dev/null ); then
              echo 'true'
            else
              echo 'false'
            fi
          )" >> $GITHUB_ENV

      - name: Create a release
        if: env.release-exists == 'false'
        run: gh release create ${{ inputs.tag }} --repo ${{ inputs.gh-org }}/keycloak-nodejs-connect --title ${{ inputs.tag }} --draft ${{ inputs.nightly && '--prerelease' || '' }}


  show-output:
    name: Show Output
    runs-on: ubuntu-latest
    needs: [create-tags,create-gh-releases]
    steps:
      - run: |
          echo "https://github.com/${{ inputs.gh-org }}/keycloak-nodejs-connect/tree/${{ inputs.tag }}  " >> $GITHUB_STEP_SUMMARY        
